// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zAQ8zXuizMrteygO4t12RZxa9PDvQWg',
    appId: '1:415059245540:web:a3a58fe70c3eb54c7aeff1',
    messagingSenderId: '415059245540',
    projectId: 'flut-cad5b',
    authDomain: 'flut-cad5b.firebaseapp.com',
    storageBucket: 'flut-cad5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOTllOtSK_VzKymDeN3c2B7TqGGfUB67s',
    appId: '1:415059245540:android:0a00e37cbc68f8f87aeff1',
    messagingSenderId: '415059245540',
    projectId: 'flut-cad5b',
    storageBucket: 'flut-cad5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyn9oVm60ifYnhhFW7UtmCP81Se5HY22U',
    appId: '1:415059245540:ios:790bb3c407e480557aeff1',
    messagingSenderId: '415059245540',
    projectId: 'flut-cad5b',
    storageBucket: 'flut-cad5b.firebasestorage.app',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyn9oVm60ifYnhhFW7UtmCP81Se5HY22U',
    appId: '1:415059245540:ios:790bb3c407e480557aeff1',
    messagingSenderId: '415059245540',
    projectId: 'flut-cad5b',
    storageBucket: 'flut-cad5b.firebasestorage.app',
    iosBundleId: 'com.example.flut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6zAQ8zXuizMrteygO4t12RZxa9PDvQWg',
    appId: '1:415059245540:web:fed872af8a7e8f1c7aeff1',
    messagingSenderId: '415059245540',
    projectId: 'flut-cad5b',
    authDomain: 'flut-cad5b.firebaseapp.com',
    storageBucket: 'flut-cad5b.firebasestorage.app',
  );
}
